#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#

development:
  adapter: mysql2
  database: trusty_blank_dev
  username: root
  password:
  host: localhost

test: &TEST
  adapter: mysql2
  database: trusty_blank_test
  username: root
  password:
  host:

production:
  adapter: mysql2
  database: trusty_blank_live
  username:
  password:
  socket: /tmp/mysql.sock

cucumber:
  <<: *TEST
